[package]
name = "findex"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
incremental = true

[profile.release]
incremental = true
lto = true

[dependencies]
gtk = { version = "0.14.3", features=["v3_22"] }
freedesktop_entry_parser = "1.2.0"
regex = "1"
shlex = "1.1.0"
nix = "0.23"
shellexpand = "2.1.0"
fuse-rust = "0.3.0"
